spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
server:
  port: ${SERVER_PORT}
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      stack.auto: false
      region.static: ${AWS_REGION}
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}